apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wordpress
spec:
  virtualhost:
    fqdn: wordpress.h2o-2-3935.h2o.vmware.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: wordpress
          port: 80