apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cache-config.fullname" .}}
  labels:
    {{- include "risk.labels" . | nindent 4 }}
data:
  RedisConnection: {{ include "redis.connection" .}}
