apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db-config.fullname" .}}
  labels:
    {{- include "risk.labels" . | nindent 4 }}
data:
  Host: {{ include "mongo.host" .}}
  MainHostConnection: {{ include "mongo.connection" . }}
  DEFAULT_DATASOURCE_KIND: Mongo
  EibConnectionStringsOption__StagingDbConnectionString: {{ include "mongo.connection" . }}/EibFinMetric_Staging/?connectTimeoutMS=60000000&waitQueueTimeoutMS=60000000&maxPoolSize=1024&minPoolSize=1024
