apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.flexera.com: krm
    app.kubernetes.io/name: flexera-krm
    app.kubernetes.io/part-of: FNMS
    
  name: controller
  namespace: flexera
secrets:
- name: controller-token-r277k
