apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fSwKCQkibmV4dXNkb2NrZXJob3N0ZWQuc3lzLm91cnRlc2NvLmNvbSI6IHsKCQkJImF1dGgiOiAiWWkxYVNFMXRjMVU2ZGxsR1FXNXNTV3hPYWpWbWFERlNhVFJrUjNOUlpGVnNNa0ZGTmpjM1IzWm1OamRuWHpocGFETnhUM1k9IgoJCX0sCgkJIm5leHVzZG9ja2VycHJpdmF0ZS5zeXMub3VydGVzY28uY29tIjogewoJCQkiYXV0aCI6ICJZaTFhU0UxdGMxVTZkbGxHUVc1c1NXeE9halZtYURGU2FUUmtSM05SWkZWc01rRkZOamMzUjNabU5qZG5YemhwYUROeFQzWT0iCgkJfQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0K
kind: Secret
metadata:
  name: svc-nexus-flexeraimagepull
  namespace: flexera
type: kubernetes.io/dockerconfigjson
