apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.flexera.com: krm
    app.kubernetes.io/name: flexera-krm
    app.kubernetes.io/part-of: FNMS
  name: flexera-krm-controller
rules:
- apiGroups:
  - agents.flexera.com
  resources:
  - krms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.flexera.com
  resources:
  - krms/status
  - krms/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - statefulsets/finalizers
  - daemonsets
  - daemonsets/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
