apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.flexera.com: krm
    app.kubernetes.io/name: flexera-krm
    app.kubernetes.io/part-of: FNMS
  name: flexera-krm-agent-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: agent
  namespace: flexera
